### PR TITLE
Fix #25/print changes to stdout

### LINKED ISSUE #25: print changes on stdout
I run this now part of the tox steps (seed --check, black --check, isort --check). Currently when this command fails leaves you wondering what would actually change, can we print to the standard output the changes to the list (maybe via some verbose mode or by default)?

### PR DESCRIPTION
**Pull request by Cielquan**
### Problem:
see #25 

### Solution:
Added '--verbose' flag. When set output is printed, when an existing config file is changed.
Output mentions the filename, added and removed modules.

Updated test cases for changed regex and added test case for verbose output.

fixes #25

### CODE REVIEW

**Comment by Cielquan** [comment]
This branch is based on the branch in pull request #63 .

**Comment by asottile** [comment]
the expectation for #25 was just a one line `print(f'{filename} updated.')`

**Comment by asottile** [comment]
please also separate out your changes, I can't merge this when it's based on somethign else

**Comment by Cielquan** [comment]
> the expectation for #25 was just a one line `print(f'{filename} updated.')` -- no new options please

I will edit it into a 2 step thing ok? 
`-v/--verbose` -> one liner
`-vv/--verbose --verbose` -> three liner

> please also separate out your changes, I can't merge this when it's based on somethign else

I will. Sorry.

**Comment by asottile** [comment]
please don't add an option

**Comment by Cielquan** [comment]
I rebased the branch to exclude #63 .

Made requested changes into new PR #65 .

**Pull request closed without merging**
